# DS-Tutor Getting Started

Welcome to DS-Tutor! This notebook will guide you through your first learning session.

## What is DS-Tutor?

DS-Tutor is an AI-powered learning system that teaches you Data Science right here in Jupyter notebooks.

**Features:**
- 📚 Progressive curriculum from beginner to advanced
- 🤖 AI-powered hints and feedback
- ✅ Automatic code validation
- 📊 Progress tracking
- 🎯 Hands-on exercises with real code

## Step 1: Load the Extension

Run the cell below to load DS-Tutor:

In [4]:
%cd ..

E:\DS-tutor


In [5]:
%load_ext src

You should see a colorful welcome message! 🎉

## Step 2: Initialize DS-Tutor

Initialize your learning environment:

In [6]:
%dstutor init

## Step 3: Explore Available Topics

Let's see what you can learn:

In [7]:
%dstutor topics

## Step 4: Start Learning NumPy

Let's begin with NumPy, the foundation of numerical computing in Python:

In [9]:
%dstutor start numpy

# NumPy Array Creation

Learn how to create NumPy arrays - the foundation of numerical computing in Python.

## What are NumPy Arrays?

NumPy arrays are powerful n-dimensional array objects that allow for efficient numerical operations.

**Key Benefits:**
- Fast vectorized operations
- Memory efficient
- Mathematical operations are intuitive
- Foundation for pandas, scikit-learn, and more

### 💡 Example: Creating Arrays from Lists

```python
import numpy as np

# 1D array
arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)
print(f"Shape: {arr1d.shape}, Dtype: {arr1d.dtype}")

# 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)
print(f"Shape: {arr2d.shape}")
```

**Expected Output:**
```
[1 2 3 4 5]
Shape: (5,), Dtype: int64
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
```


---

## ✏️ Exercise

Create a 1D NumPy array containing the numbers 10, 20, 30, 40, 50 and store it in a variable called `result`.

**Setup Code** (Run this first):


```python
import numpy as np
```


**Your Solution:**

```python\n# Your code here
result = \n```

---
💡 **Tip:** Use `%dstutor hint` if you need help!


Output()

The lesson content will appear above! 📚

Read through the explanation and examples, then try the exercise below.

## Step 5: Try the Exercise

Now it's your turn! Write code to solve the exercise.

**Exercise:** Create a NumPy array with values [10, 20, 30, 40, 50]

In [11]:
# Your code here
import numpy as np

result = np.array([10, 20, 30, 40, 50])

When you run the cell above, DS-Tutor will automatically validate your solution and give you feedback!

## Getting Help

### Need a hint?

If you're stuck, get a hint:

In [12]:
%dstutor hint

### Need more help?

In [13]:
%dstutor hint 2  # More specific hint

### Want to see the solution?

In [14]:
%dstutor solution

## Navigation

### Move to the next lesson:

In [15]:
%dstutor next

# NumPy Array Creation Functions

Learn efficient ways to create arrays using NumPy functions.

## Array Creation Functions

NumPy provides many functions for creating arrays:

- `np.zeros()` - Array filled with zeros
- `np.ones()` - Array filled with ones
- `np.arange()` - Array with evenly spaced values
- `np.linspace()` - Array with specified number of values
- `np.eye()` - Identity matrix

### 💡 Example: Using Creation Functions

```python
import numpy as np

# Array of zeros
zeros = np.zeros((3, 4))
print("Zeros:")
print(zeros)

# Array of ones
ones = np.ones((2, 3))
print("\nOnes:")
print(ones)

# Range of values
range_arr = np.arange(0, 10, 2)
print("\nRange:", range_arr)
```

**Expected Output:**
```
Arrays with specified values
```


---

## ✏️ Exercise

Create a 2D array filled with zeros, with shape (3, 5). Store it in a variable called `result`.

**Setup Code** (Run this first):


```python
import numpy as np
```


**Your Solution:**

```python\n# Your code here
result = \n```

---
💡 **Tip:** Use `%dstutor hint` if you need help!


Output()

### Go back to the previous lesson:

In [17]:
%dstutor previous

## Track Your Progress

View your learning progress:

In [18]:
%dstutor progress

## All Available Commands

Get a complete list of commands:

In [19]:
%dstutor help

## Tips for Success

1. **Try it yourself first** - Don't jump to hints immediately
2. **Experiment** - Modify examples to see what happens
3. **Practice daily** - Even 15-20 minutes helps
4. **Take notes** - Add your own markdown cells
5. **Review regularly** - Go back to reinforce concepts

---

## Ready to Learn?

You now know the basics! Here's your learning path:

### Level 1: Foundations
- ✅ **NumPy Mastery** - Array manipulation (Start here!)
- **Pandas Deep Dive** - Data manipulation
- **Matplotlib & Seaborn** - Data visualization

### Level 2: ML Pipeline
- **EDA** - Exploratory Data Analysis
- **Preprocessing** - Data cleaning
- **Scikit-Learn** - Machine learning models

### Level 3: Advanced
- **Deep Learning** - Keras & PyTorch
- **Model Interpretation** - SHAP, LIME
- **Specialized Topics** - Time series, NLP, CV

---

## Let's Begin!

Start your Data Science journey right now:

In [20]:
# Start learning!
%dstutor start numpy

# NumPy Array Creation

Learn how to create NumPy arrays - the foundation of numerical computing in Python.

## What are NumPy Arrays?

NumPy arrays are powerful n-dimensional array objects that allow for efficient numerical operations.

**Key Benefits:**
- Fast vectorized operations
- Memory efficient
- Mathematical operations are intuitive
- Foundation for pandas, scikit-learn, and more

### 💡 Example: Creating Arrays from Lists

```python
import numpy as np

# 1D array
arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)
print(f"Shape: {arr1d.shape}, Dtype: {arr1d.dtype}")

# 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)
print(f"Shape: {arr2d.shape}")
```

**Expected Output:**
```
[1 2 3 4 5]
Shape: (5,), Dtype: int64
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
```


---

## ✏️ Exercise

Create a 1D NumPy array containing the numbers 10, 20, 30, 40, 50 and store it in a variable called `result`.

**Setup Code** (Run this first):


```python
import numpy as np
```


**Your Solution:**

```python\n# Your code here
result = \n```

---
💡 **Tip:** Use `%dstutor hint` if you need help!


Output()

---

**Happy Learning! 🎓📊🤖**

Remember: The journey of a thousand miles begins with a single step. Your Data Science journey starts here!